// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type PublicKey struct {
	ID        int64
	Name      string
	PublicKey string
}

type Stikky struct {
	ID            int64
	RsaPrivateKey string
	RsaPublicKey  string
}
