// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getPublicKeys = `-- name: GetPublicKeys :many
SELECT id, name, public_key FROM public_keys
`

func (q *Queries) GetPublicKeys(ctx context.Context) ([]PublicKey, error) {
	rows, err := q.db.QueryContext(ctx, getPublicKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublicKey
	for rows.Next() {
		var i PublicKey
		if err := rows.Scan(&i.ID, &i.Name, &i.PublicKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStikky = `-- name: GetStikky :one
SELECT id, rsa_private_key, rsa_public_key FROM stikky ORDER BY id ASC LIMIT 1
`

func (q *Queries) GetStikky(ctx context.Context) (Stikky, error) {
	row := q.db.QueryRowContext(ctx, getStikky)
	var i Stikky
	err := row.Scan(&i.ID, &i.RsaPrivateKey, &i.RsaPublicKey)
	return i, err
}
